course_id = 15407
course_name = "Mechatronics"
course_code = "TMRK16"
credits = "7.5 ECTS"
semester = "Spring 2026"
canvas_api_url = "https://ju.instructure.com"
canvas_token_path = "C:\\Users\\mirza\\privateCanvasToken"
language = "english"
