---
title: "PWM Visualizer"
format:
  html:
    page-layout: custom
    minimal: true
    embed-resources: true
    toc: false
    margin-top: 0
    margin-bottom: 0
execute:
  echo: false
---

<div style="display: flex; align-items: center; flex-direction: column; font-family: sans-serif; padding: 10px;">
  <div style="display: flex; align-items: center;">
    <div style="margin-right: 30px;">
      <p>Average motor voltage: <strong><span id="avg-voltage">6.00V</span></strong> / 12V</p>
    </div>
    <canvas id="pwm-canvas" width="400" height="200" style="border: 1px solid #ccc;"></canvas>
    <div style="margin-left: 30px;">
      <div id="duty-cycle-circle" style="background-color: rgb(128,128,0); width: 50px; height: 50px; border-radius: 50%; margin-top: 10px;"></div>
      <div style="display: flex; align-items: center; justify-content: center; margin-top: 20px;">Motor</div>
    </div>
  </div>
  <div style="display: flex; align-items: center; justify-content: center; margin-top: 20px;">
    <p style="margin-right: 10px;">PWM Duty Cycle:</p>
    <input type="range" min="0" max="100" value="50" step="0.390625" id="duty-cycle-slider">
    <p style="margin-left: 10px;"><strong><span id="duty-cycle-percentage">50.00 %</span></strong></p>
  </div>
  <div style="display: flex; align-items: center; justify-content: center; margin-top: 10px;">
    <p style="margin-right: 10px;">PWM Frequency:</p>
    <input type="range" min="1" max="15" value="3" step="0.1" id="frequency-slider">
    <p style="margin-left: 10px;"><span id="frequency-value">3.0 Hz</span></p>
  </div>
  <div style="display: flex; align-items: center; justify-content: center; margin-top: 10px; margin-bottom: 20px;">
    <p style="margin-right: 10px;">PWM Resolution:</p>
    <select id="duty-cycle-resolution">
      <option value="2">2 bits</option>
      <option value="3">3 bits</option>
      <option value="4">4 bits</option>
      <option value="5">5 bits</option>
      <option value="6">6 bits</option>
      <option value="8" selected="">8 bits</option>
      <option value="10">10 bits</option>
      <option value="16">16 bits</option>
    </select>
  </div>
</div>

<script>
  const canvas = document.getElementById('pwm-canvas');
  const context = canvas.getContext('2d');
  const width = canvas.width;
  const height = canvas.height;
  let frequency = 3;
  let dutyCycle = 0.5;

  function updatePlot() {
    const plotData = [];
    let sum = 0;
    for (let i = 0; i < width; i++) {
      const value = i % (width / frequency) < (width / frequency) * dutyCycle ? 1 : -1;
      plotData.push(value);
      sum += value;
    }

    context.lineWidth = 1.5;
    context.setLineDash([]);
    context.strokeStyle = 'red';
    context.clearRect(0, 0, width, height);
    context.beginPath();
    context.moveTo(0, height / 2);
    for (let i = 1; i < plotData.length; i++) {
      context.lineTo(i, height / 2 - plotData[i] * height / 4);
    }
    context.stroke();

    context.beginPath();
    context.setLineDash([5, 5]);
    context.lineWidth = 2;
    context.strokeStyle = 'black';
    context.moveTo(0, height / 2 - sum / plotData.length * height / 4);
    context.lineTo(width, height / 2 - sum / plotData.length * height / 4);
    context.stroke();

    document.getElementById('avg-voltage').textContent = (dutyCycle * 12).toFixed(2) + 'V';
    document.getElementById('duty-cycle-percentage').textContent = (dutyCycle * 100).toFixed(2) + ' %';
    document.getElementById('frequency-value').textContent = parseFloat(frequency).toFixed(1) + ' Hz';

    const redValue = Math.round(255 * dutyCycle);
    document.getElementById('duty-cycle-circle').style.backgroundColor = 'rgb(' + redValue + ',' + redValue + ',0)';

    const steps = Math.pow(2, parseInt(document.getElementById('duty-cycle-resolution').value));
    document.getElementById('duty-cycle-slider').step = (100 / steps).toString();
  }

  updatePlot();

  document.getElementById('frequency-slider').addEventListener('input', function() {
    frequency = parseFloat(this.value);
    updatePlot();
  });
  document.getElementById('duty-cycle-slider').addEventListener('input', function() {
    dutyCycle = parseFloat(this.value) / 100;
    updatePlot();
  });
  document.getElementById('duty-cycle-resolution').addEventListener('change', function() {
    updatePlot();
  });
</script>
